sudo: false
language: java
jdk: oraclejdk8
cache:
    apt: true
    directories:
        - $HOME/.m2
script: mvn clean verify -Pjacoco coveralls:report
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
notifications:
  slack: cunyponder:3OfGEYTotEt5lUkewK49szDE
